- id: gen-readme
  name: gen-readme
  entry: gen-readme
  language: python
  types: [text]
  require_serial: false
  args:
    - "--org-name"
    - "--repo-name"
    - "--branch"
    - "--addons-dir"
    - "--gen-html"
